
package br.gov.go.goiania.sefin.infoconv.pojo.cnpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ConsultarCNPJSoap", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ConsultarCNPJSoap {


    /**
     * Consultar CNPJ - Perfil DEC8789
     * 			
     * 
     * @param cpfUsuario
     * @param cnpj
     * @return
     *     returns br.gov.go.goiania.sefin.pojo.cnpj.ArrayOfCNPJPerfilDEC8789
     */
    @WebMethod(operationName = "ConsultarCNPJPDEC8789", action = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/ConsultarCNPJPDEC8789")
    @WebResult(name = "ConsultarCNPJPDEC8789Result", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/")
    @RequestWrapper(localName = "ConsultarCNPJPDEC8789", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.go.goiania.sefin.pojo.cnpj.ConsultarCNPJPDEC8789")
    @ResponseWrapper(localName = "ConsultarCNPJPDEC8789Response", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/", className = "br.gov.go.goiania.sefin.pojo.cnpj.ConsultarCNPJPDEC8789Response")
    public ArrayOfCNPJPerfilDEC8789 consultarCNPJPDEC8789(
        @WebParam(name = "CNPJ", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/")
        String cnpj,
        @WebParam(name = "CPFUsuario", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cnpj/")
        String cpfUsuario);

}
