
package br.gov.go.goiania.sefin.infoconv.pojo.cpf;

import java.net.MalformedURLException;
import java.net.URL;
import java.security.GeneralSecurityException;
import java.security.SecureRandom;
import javax.net.ssl.*;
import javax.xml.namespace.QName;
import javax.xml.ws.*;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.2
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ConsultarCPF", targetNamespace = "https://acesso.infoconv.receita.fazenda.gov.br/ws/cpf/", wsdlLocation = "file:/C:/prefeitura/infoconv/src/main/resources/infoconv_cpf.wsdl")
public class ConsultarCPFService
    extends Service
{

    private final static URL CONSULTARCPF_WSDL_LOCATION;
    private final static WebServiceException CONSULTARCPF_EXCEPTION;
    private final static QName CONSULTARCPF_QNAME = new QName("https://acesso.infoconv.receita.fazenda.gov.br/ws/cpf/", "ConsultarCPF");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            javax.net.ssl.HttpsURLConnection.setDefaultSSLSocketFactory(getTrustingSSLSocketFactory());

            url = new URL("file:/C:/prefeitura/infoconv/src/main/resources/infoconv_cpf.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CONSULTARCPF_WSDL_LOCATION = url;
        CONSULTARCPF_EXCEPTION = e;
    }

    public ConsultarCPFService() {
        super(__getWsdlLocation(), CONSULTARCPF_QNAME);
    }

    public ConsultarCPFService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CONSULTARCPF_QNAME, features);
    }

    public ConsultarCPFService(URL wsdlLocation) {
        super(wsdlLocation, CONSULTARCPF_QNAME);
    }

    public ConsultarCPFService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CONSULTARCPF_QNAME, features);
    }

    public ConsultarCPFService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ConsultarCPFService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ConsultarCPFSoap
     */
    @WebEndpoint(name = "ConsultarCPFSoap")
    public ConsultarCPFSoap getConsultarCPFSoap() {
        return super.getPort(new QName("https://acesso.infoconv.receita.fazenda.gov.br/ws/cpf/", "ConsultarCPFSoap"), ConsultarCPFSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ConsultarCPFSoap
     */
    @WebEndpoint(name = "ConsultarCPFSoap")
    public ConsultarCPFSoap getConsultarCPFSoap(WebServiceFeature... features) {
        return super.getPort(new QName("https://acesso.infoconv.receita.fazenda.gov.br/ws/cpf/", "ConsultarCPFSoap"), ConsultarCPFSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CONSULTARCPF_EXCEPTION!= null) {
            throw CONSULTARCPF_EXCEPTION;
        }
        return CONSULTARCPF_WSDL_LOCATION;
    }

    private static SSLSocketFactory getTrustingSSLSocketFactory() {
        return ConsultarCPFService.SSLSocketFactoryHolder.INSTANCE;
    }

    private static interface SSLSocketFactoryHolder {
        public static final SSLSocketFactory INSTANCE = createSSLSocketFactory();
    }

    private static SSLSocketFactory createSSLSocketFactory() {
        TrustManager[] trustManagers = new TrustManager[] { new ConsultarCPFService.NaiveTrustManager() };
        SSLContext sslContext;
        try {
            sslContext = SSLContext.getInstance("SSL");
            sslContext.init(new KeyManager[0], trustManagers, new SecureRandom());
            return sslContext.getSocketFactory();
        } catch (GeneralSecurityException e) {
            System.err.println(e.getMessage());
            return null;
        }
    }

    private static class NaiveTrustManager implements X509TrustManager {
        @Override
        public void checkClientTrusted(java.security.cert.X509Certificate[] certs, String authType) throws java.security.cert.CertificateException {
        }

        @Override
        public void checkServerTrusted(java.security.cert.X509Certificate[] certs, String authType) throws java.security.cert.CertificateException {
        }

        @Override
        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
            return new java.security.cert.X509Certificate[0];
        }
    }
}
